### ISSUE TITLE
gem install co2mon

### ISSUE THREAD

**Issue by do11** [arkadiybutermanov/co2mond#1]
```
root@wqe:~# gem install co2mon
Building native extensions. This could take a while...
Successfully installed co2mon-0.2.0
Parsing documentation for co2mon-0.2.0
Done installing documentation for co2mon after 0 seconds
1 gem installed
root@qwe:~# irb
irb(main):001:0> require 'co2mon'
Traceback (most recent call last):
       10: from /usr/bin/irb:11:in `<main>'
        9: from (irb):1
        8: from /usr/lib/ruby/rubygems/core_ext/kernel_require.rb:39:in `require'
        7: from /usr/lib/ruby/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        6: from /usr/lib/ruby/rubygems/core_ext/kernel_require.rb:135:in `require'
        5: from /usr/lib/ruby/gems/2.5.0/gems/co2mon-0.2.0/lib/co2mon.rb:4:in `<top (required)>'
        4: from /usr/lib/ruby/gems/2.5.0/gems/co2mon-0.2.0/lib/co2mon.rb:7:in `<module:Co2mon>'
        3: from /usr/lib/ruby/gems/2.5.0/gems/ffi-1.9.23/lib/ffi/library.rb:100:in `ffi_lib'
        2: from /usr/lib/ruby/gems/2.5.0/gems/ffi-1.9.23/lib/ffi/library.rb:100:in `map'
        1: from /usr/lib/ruby/gems/2.5.0/gems/ffi-1.9.23/lib/ffi/library.rb:147:in `block in ffi_lib'
LoadError (Could not open library '/usr/lib/ruby/gems/2.5.0/gems/co2mon-0.2.0/lib/co2mon.bundle': /usr/lib/ruby/gems/2.5.0/gems/co2mon-0.2.0/lib/co2mon.bundle: cannot open shared object file: No such file or directory)
irb(main):002:0>
```

**Comment by do11** [comment]
Probably, you meant `co2mon.so` instead of `co2mon.bundle`. And to compile with `-lhidapi-libusb`.
